package com.tsingxu.test.protobuf;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

public final class Person {
	private Person() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface OrderOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int32 time = 1;
		/**
		 * <code>required int32 time = 1;</code>
		 */
		boolean hasTime();

		/**
		 * <code>required int32 time = 1;</code>
		 */
		int getTime();

		// required int32 userid = 2;
		/**
		 * <code>required int32 userid = 2;</code>
		 */
		boolean hasUserid();

		/**
		 * <code>required int32 userid = 2;</code>
		 */
		int getUserid();

		// required float price = 3;
		/**
		 * <code>required float price = 3;</code>
		 */
		boolean hasPrice();

		/**
		 * <code>required float price = 3;</code>
		 */
		float getPrice();

		// optional string desc = 4;
		/**
		 * <code>optional string desc = 4;</code>
		 */
		boolean hasDesc();

		/**
		 * <code>optional string desc = 4;</code>
		 */
		java.lang.String getDesc();

		/**
		 * <code>optional string desc = 4;</code>
		 */
		com.google.protobuf.ByteString getDescBytes();
	}

	/**
	 * Protobuf type {@code Order}
	 */
	public static final class Order extends
			com.google.protobuf.GeneratedMessage implements OrderOrBuilder {
		// Use Order.newBuilder() to construct.
		private Order(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private Order(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet
					.getDefaultInstance();
		}

		private static final Order defaultInstance;

		public static Order getDefaultInstance() {
			return defaultInstance;
		}

		public Order getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Order(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						time_ = input.readInt32();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						userid_ = input.readInt32();
						break;
					}
					case 29: {
						bitField0_ |= 0x00000004;
						price_ = input.readFloat();
						break;
					}
					case 34: {
						bitField0_ |= 0x00000008;
						desc_ = input.readBytes();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return Person.internal_static_Order_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return Person.internal_static_Order_fieldAccessorTable
					.ensureFieldAccessorsInitialized(Person.Order.class,
							Person.Order.Builder.class);
		}

		public static com.google.protobuf.Parser<Order> PARSER = new com.google.protobuf.AbstractParser<Order>() {
			public Order parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Order(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<Order> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required int32 time = 1;
		public static final int TIME_FIELD_NUMBER = 1;
		private int time_;

		/**
		 * <code>required int32 time = 1;</code>
		 */
		public boolean hasTime() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int32 time = 1;</code>
		 */
		public int getTime() {
			return time_;
		}

		// required int32 userid = 2;
		public static final int USERID_FIELD_NUMBER = 2;
		private int userid_;

		/**
		 * <code>required int32 userid = 2;</code>
		 */
		public boolean hasUserid() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required int32 userid = 2;</code>
		 */
		public int getUserid() {
			return userid_;
		}

		// required float price = 3;
		public static final int PRICE_FIELD_NUMBER = 3;
		private float price_;

		/**
		 * <code>required float price = 3;</code>
		 */
		public boolean hasPrice() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>required float price = 3;</code>
		 */
		public float getPrice() {
			return price_;
		}

		// optional string desc = 4;
		public static final int DESC_FIELD_NUMBER = 4;
		private java.lang.Object desc_;

		/**
		 * <code>optional string desc = 4;</code>
		 */
		public boolean hasDesc() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		/**
		 * <code>optional string desc = 4;</code>
		 */
		public java.lang.String getDesc() {
			java.lang.Object ref = desc_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					desc_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string desc = 4;</code>
		 */
		public com.google.protobuf.ByteString getDescBytes() {
			java.lang.Object ref = desc_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				desc_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			time_ = 0;
			userid_ = 0;
			price_ = 0F;
			desc_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasTime()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasUserid()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasPrice()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, time_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(2, userid_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeFloat(3, price_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBytes(4, getDescBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						1, time_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						2, userid_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeFloatSize(
						3, price_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						4, getDescBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static Person.Order parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Person.Order parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Person.Order parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Person.Order parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Person.Order parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static Person.Order parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Person.Order parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static Person.Order parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static Person.Order parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static Person.Order parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(Person.Order prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code Order}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				Person.OrderOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return Person.internal_static_Order_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return Person.internal_static_Order_fieldAccessorTable
						.ensureFieldAccessorsInitialized(Person.Order.class,
								Person.Order.Builder.class);
			}

			// Construct using Person.Order.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				time_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				userid_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				price_ = 0F;
				bitField0_ = (bitField0_ & ~0x00000004);
				desc_ = "";
				bitField0_ = (bitField0_ & ~0x00000008);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return Person.internal_static_Order_descriptor;
			}

			public Person.Order getDefaultInstanceForType() {
				return Person.Order.getDefaultInstance();
			}

			public Person.Order build() {
				Person.Order result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public Person.Order buildPartial() {
				Person.Order result = new Person.Order(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.time_ = time_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.userid_ = userid_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.price_ = price_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.desc_ = desc_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Person.Order) {
					return mergeFrom((Person.Order) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Person.Order other) {
				if (other == Person.Order.getDefaultInstance())
					return this;
				if (other.hasTime()) {
					setTime(other.getTime());
				}
				if (other.hasUserid()) {
					setUserid(other.getUserid());
				}
				if (other.hasPrice()) {
					setPrice(other.getPrice());
				}
				if (other.hasDesc()) {
					bitField0_ |= 0x00000008;
					desc_ = other.desc_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasTime()) {

					return false;
				}
				if (!hasUserid()) {

					return false;
				}
				if (!hasPrice()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				Person.Order parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Person.Order) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required int32 time = 1;
			private int time_;

			/**
			 * <code>required int32 time = 1;</code>
			 */
			public boolean hasTime() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required int32 time = 1;</code>
			 */
			public int getTime() {
				return time_;
			}

			/**
			 * <code>required int32 time = 1;</code>
			 */
			public Builder setTime(int value) {
				bitField0_ |= 0x00000001;
				time_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 time = 1;</code>
			 */
			public Builder clearTime() {
				bitField0_ = (bitField0_ & ~0x00000001);
				time_ = 0;
				onChanged();
				return this;
			}

			// required int32 userid = 2;
			private int userid_;

			/**
			 * <code>required int32 userid = 2;</code>
			 */
			public boolean hasUserid() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required int32 userid = 2;</code>
			 */
			public int getUserid() {
				return userid_;
			}

			/**
			 * <code>required int32 userid = 2;</code>
			 */
			public Builder setUserid(int value) {
				bitField0_ |= 0x00000002;
				userid_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 userid = 2;</code>
			 */
			public Builder clearUserid() {
				bitField0_ = (bitField0_ & ~0x00000002);
				userid_ = 0;
				onChanged();
				return this;
			}

			// required float price = 3;
			private float price_;

			/**
			 * <code>required float price = 3;</code>
			 */
			public boolean hasPrice() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>required float price = 3;</code>
			 */
			public float getPrice() {
				return price_;
			}

			/**
			 * <code>required float price = 3;</code>
			 */
			public Builder setPrice(float value) {
				bitField0_ |= 0x00000004;
				price_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required float price = 3;</code>
			 */
			public Builder clearPrice() {
				bitField0_ = (bitField0_ & ~0x00000004);
				price_ = 0F;
				onChanged();
				return this;
			}

			// optional string desc = 4;
			private java.lang.Object desc_ = "";

			/**
			 * <code>optional string desc = 4;</code>
			 */
			public boolean hasDesc() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>optional string desc = 4;</code>
			 */
			public java.lang.String getDesc() {
				java.lang.Object ref = desc_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					desc_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string desc = 4;</code>
			 */
			public com.google.protobuf.ByteString getDescBytes() {
				java.lang.Object ref = desc_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					desc_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string desc = 4;</code>
			 */
			public Builder setDesc(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				desc_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string desc = 4;</code>
			 */
			public Builder clearDesc() {
				bitField0_ = (bitField0_ & ~0x00000008);
				desc_ = getDefaultInstance().getDesc();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string desc = 4;</code>
			 */
			public Builder setDescBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				desc_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:Order)
		}

		static {
			defaultInstance = new Order(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:Order)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_Order_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_Order_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\014person.proto\"B\n\005Order\022\014\n\004time\030\001 \002(\005\022\016\n"
				+ "\006userid\030\002 \002(\005\022\r\n\005price\030\003 \002(\002\022\014\n\004desc\030\004 \001"
				+ "(\t" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_Order_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_Order_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_Order_descriptor,
						new java.lang.String[] { "Time", "Userid", "Price",
								"Desc", });
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
